name: SonarQube & Publish NuGet Package

env:
  DOTNET_VERSION: '8.0.x'
  SONAR_ORG: 'apibankk'
  SONAR_PROJECT: 'apibankk_apibank'
  PACKAGE_NAME: 'MiPaquete.ApiBank'
  PACKAGE_VERSION: '1.0.0'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build, Test, Sonar, Pack, Publish & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java (Sonar necesita Java)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Start SonarCloud analysis
        run: |
          dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
            /d:sonar.qualitygate.wait=true

      - name: Restore, Test and Build
        run: |
          dotnet restore
          dotnet test --collect:"XPlat Code Coverage;Format=opencover"
          dotnet build --no-restore

      - name: End SonarCloud analysis
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Add GitHub NuGet source
        run: |
          dotnet nuget add source --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github "https://nuget.pkg.github.com/mayrafc/index.json"

      - name: Push NuGet package to GitHub Packages
        run: |
          dotnet nuget push ./nupkg/${{ env.PACKAGE_NAME }}.${{ env.PACKAGE_VERSION }}.nupkg \
            --source github \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate

      - name: Generate Changelog from Commits
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          git log --pretty=format:"- %s" --no-merges -10 >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ env.PACKAGE_VERSION }}"
          gh release create "v$VERSION" \
            --title "Release v$VERSION" \
            --notes "${{ env.CHANGELOG }}" \
            ./nupkg/${{ env.PACKAGE_NAME }}.${{ env.PACKAGE_VERSION }}.nupkg
